# XXX WIP as we default to clang!
#
# Need these for a more recent CMake on Linux
sudo: required
dist: xenial

os:
  - linux

language: cpp

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build build

after_script:
  - cmake --build build --target test

